import { memo } from "react";

import { engagementlistmockdata } from "../../components/GanttChart/engagementlistmockdata";
import { memoizedCalendarData } from "../calendarHelper";

const memoizedProjectEngagementData = {
  earliestStartDate: "2021-01-16T14:01:22.000Z",
  latestEndDate: "2023-09-24T08:22:20.099Z",
  info: {
    calendarWidth: { monthly: 43800, weekly: 24180, yearly: 4464 },
    calendarHeader: {
      monthly: [
        {
          year: "2021",
          month: "JAN",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2021",
          month: "FEB",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
          ],
        },
        {
          year: "2021",
          month: "MAR",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2021",
          month: "APR",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
          ],
        },
        {
          year: "2021",
          month: "MAY",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2021",
          month: "JUN",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
          ],
        },
        {
          year: "2021",
          month: "JUL",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2021",
          month: "AUG",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2021",
          month: "SEP",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
          ],
        },
        {
          year: "2021",
          month: "OCT",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2021",
          month: "NOV",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
          ],
        },
        {
          year: "2021",
          month: "DEC",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2022",
          month: "JAN",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2022",
          month: "FEB",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
          ],
        },
        {
          year: "2022",
          month: "MAR",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2022",
          month: "APR",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
          ],
        },
        {
          year: "2022",
          month: "MAY",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2022",
          month: "JUN",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
          ],
        },
        {
          year: "2022",
          month: "JUL",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2022",
          month: "AUG",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2022",
          month: "SEP",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
          ],
        },
        {
          year: "2022",
          month: "OCT",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2022",
          month: "NOV",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
          ],
        },
        {
          year: "2022",
          month: "DEC",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2023",
          month: "JAN",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2023",
          month: "FEB",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
          ],
        },
        {
          year: "2023",
          month: "MAR",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2023",
          month: "APR",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
          ],
        },
        {
          year: "2023",
          month: "MAY",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: true },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2023",
          month: "JUN",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
          ],
        },
        {
          year: "2023",
          month: "JUL",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2023",
          month: "AUG",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2023",
          month: "SEP",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
          ],
        },
        {
          year: "2023",
          month: "OCT",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
        {
          year: "2023",
          month: "NOV",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
          ],
        },
        {
          year: "2023",
          month: "DEC",
          days: [
            { day: 1, isToday: false },
            { day: 2, isToday: false },
            { day: 3, isToday: false },
            { day: 4, isToday: false },
            { day: 5, isToday: false },
            { day: 6, isToday: false },
            { day: 7, isToday: false },
            { day: 8, isToday: false },
            { day: 9, isToday: false },
            { day: 10, isToday: false },
            { day: 11, isToday: false },
            { day: 12, isToday: false },
            { day: 13, isToday: false },
            { day: 14, isToday: false },
            { day: 15, isToday: false },
            { day: 16, isToday: false },
            { day: 17, isToday: false },
            { day: 18, isToday: false },
            { day: 19, isToday: false },
            { day: 20, isToday: false },
            { day: 21, isToday: false },
            { day: 22, isToday: false },
            { day: 23, isToday: false },
            { day: 24, isToday: false },
            { day: 25, isToday: false },
            { day: 26, isToday: false },
            { day: 27, isToday: false },
            { day: 28, isToday: false },
            { day: 29, isToday: false },
            { day: 30, isToday: false },
            { day: 31, isToday: false },
          ],
        },
      ],
      weekly: [
        { year: "2021", month: "JAN", sundays: ["3", "10", "17", "24", "31"] },
        { year: "2021", month: "FEB", sundays: ["7", "14", "21", "28"] },
        { year: "2021", month: "MAR", sundays: ["7", "14", "21", "28"] },
        { year: "2021", month: "APR", sundays: ["4", "11", "18", "25"] },
        { year: "2021", month: "MAY", sundays: ["2", "9", "16", "23", "30"] },
        { year: "2021", month: "JUN", sundays: ["6", "13", "20", "27"] },
        { year: "2021", month: "JUL", sundays: ["4", "11", "18", "25"] },
        { year: "2021", month: "AUG", sundays: ["1", "8", "15", "22", "29"] },
        { year: "2021", month: "SEP", sundays: ["5", "12", "19", "26"] },
        { year: "2021", month: "OCT", sundays: ["3", "10", "17", "24", "31"] },
        { year: "2021", month: "NOV", sundays: ["7", "14", "21", "28"] },
        { year: "2021", month: "DEC", sundays: ["5", "12", "19", "26"] },
        { year: "2022", month: "JAN", sundays: ["2", "9", "16", "23", "30"] },
        { year: "2022", month: "FEB", sundays: ["6", "13", "20", "27"] },
        { year: "2022", month: "MAR", sundays: ["6", "13", "20", "27"] },
        { year: "2022", month: "APR", sundays: ["3", "10", "17", "24"] },
        { year: "2022", month: "MAY", sundays: ["1", "8", "15", "22", "29"] },
        { year: "2022", month: "JUN", sundays: ["5", "12", "19", "26"] },
        { year: "2022", month: "JUL", sundays: ["3", "10", "17", "24", "31"] },
        { year: "2022", month: "AUG", sundays: ["7", "14", "21", "28"] },
        { year: "2022", month: "SEP", sundays: ["4", "11", "18", "25"] },
        { year: "2022", month: "OCT", sundays: ["2", "9", "16", "23", "30"] },
        { year: "2022", month: "NOV", sundays: ["6", "13", "20", "27"] },
        { year: "2022", month: "DEC", sundays: ["4", "11", "18", "25"] },
        { year: "2023", month: "JAN", sundays: ["1", "8", "15", "22", "29"] },
        { year: "2023", month: "FEB", sundays: ["5", "12", "19", "26"] },
        { year: "2023", month: "MAR", sundays: ["5", "12", "19", "26"] },
        { year: "2023", month: "APR", sundays: ["2", "9", "16", "23", "30"] },
        { year: "2023", month: "MAY", sundays: ["7", "14", "21", "28"] },
        { year: "2023", month: "JUN", sundays: ["4", "11", "18", "25"] },
        { year: "2023", month: "JUL", sundays: ["2", "9", "16", "23", "30"] },
        { year: "2023", month: "AUG", sundays: ["6", "13", "20", "27"] },
        { year: "2023", month: "SEP", sundays: ["3", "10", "17", "24"] },
        { year: "2023", month: "OCT", sundays: ["1", "8", "15", "22", "29"] },
        { year: "2023", month: "NOV", sundays: ["5", "12", "19", "26"] },
        { year: "2023", month: "DEC", sundays: ["3", "10", "17", "24", "31"] },
      ],
      yearly: [
        {
          year: "2021",
          months: [
            { month: "JANUARY", isThisMonth: false },
            { month: "FEBRUARY", isThisMonth: false },
            { month: "MARCH", isThisMonth: false },
            { month: "APRIL", isThisMonth: false },
            { month: "MAY", isThisMonth: false },
            { month: "JUNE", isThisMonth: false },
            { month: "JULY", isThisMonth: false },
            { month: "AUGUST", isThisMonth: false },
            { month: "SEPTEMBER", isThisMonth: false },
            { month: "OCTOBER", isThisMonth: false },
            { month: "NOVEMBER", isThisMonth: false },
            { month: "DECEMBER", isThisMonth: false },
          ],
        },
        {
          year: "2022",
          months: [
            { month: "JANUARY", isThisMonth: false },
            { month: "FEBRUARY", isThisMonth: false },
            { month: "MARCH", isThisMonth: false },
            { month: "APRIL", isThisMonth: false },
            { month: "MAY", isThisMonth: false },
            { month: "JUNE", isThisMonth: false },
            { month: "JULY", isThisMonth: false },
            { month: "AUGUST", isThisMonth: false },
            { month: "SEPTEMBER", isThisMonth: false },
            { month: "OCTOBER", isThisMonth: false },
            { month: "NOVEMBER", isThisMonth: false },
            { month: "DECEMBER", isThisMonth: false },
          ],
        },
        {
          year: "2023",
          months: [
            { month: "JANUARY", isThisMonth: false },
            { month: "FEBRUARY", isThisMonth: false },
            { month: "MARCH", isThisMonth: false },
            { month: "APRIL", isThisMonth: false },
            { month: "MAY", isThisMonth: true },
            { month: "JUNE", isThisMonth: false },
            { month: "JULY", isThisMonth: false },
            { month: "AUGUST", isThisMonth: false },
            { month: "SEPTEMBER", isThisMonth: false },
            { month: "OCTOBER", isThisMonth: false },
            { month: "NOVEMBER", isThisMonth: false },
            { month: "DECEMBER", isThisMonth: false },
          ],
        },
      ],
    },
  },
};

test("memoizeProjectEngagementData()", () => {
  const results = memoizedCalendarData(engagementlistmockdata);

  expect(results).toEqual(memoizedCalendarData);
});

test("memoizeProjectEngagementData() without tasks", () => {
  const data = [
    {
      id: "6438f5f51725504e53c94356",
      name: "name of the project",
      registry: {
        id: "6438f5f51725504e53c94356",
        name: "Verra",
      },
      registryProjectId: "1851",
      types: [
        {
          id: "6438f6b71725504e53c94357",
          name: "Renewables",
        },
      ],
      countries: [
        {
          id: "IN",
          name: "India",
          iso2Name: "IN",
          iso3Name: "IND",
        },
      ],
      isActive: true,
      engagements: [
        {
          id: "6438f5f51725504e53c94347",
          projectId: "6438f5f51725504e53c94356",
          type: "Registration",
          startDate: "2021-01-16T14:01:22Z",
          dueDate: "2022-05-14T14:15:22Z",
          completedDate: "2022-05-29T14:15:22Z",
          notes: "Project Document Added",
          state: "NOT_STARTED",
          stateHistory: [
            {
              state: "NOT_STARTED",
              stateUpdatedAt: "2019-08-24T14:15:22Z",
            },
          ],
          isOverdue: true,
          attributes: [
            {
              name: "Registry ID",
              type: "string",
              value: "S00208",
              key: "REGISTRY_ID",
            },
          ],
          tasks: [{}],
          createdAt: "2023-06-05T16:00:00.000Z",
          updatedAt: "2023-06-07T16:00:00.000Z",
        },
      ],
      createdAt: "2023-06-05T16:00:00.000Z",
      updatedAt: "2023-06-08T16:00:00.000Z",
    },
  ];

  const results = memoizedCalendarData(data);

  console.log(results);

  // expect(results).toEqual(memoizeProjectEngagementData);
});

test("memoizeProjectEngagementData() without engagements", () => {
  const data = [
    {
      id: "6438f5f51725504e53c94356",
      name: "name of the project",
      registry: {
        id: "6438f5f51725504e53c94356",
        name: "Verra",
      },
      registryProjectId: "1851",
      types: [
        {
          id: "6438f6b71725504e53c94357",
          name: "Renewables",
        },
      ],
      countries: [
        {
          id: "IN",
          name: "India",
          iso2Name: "IN",
          iso3Name: "IND",
        },
      ],
      isActive: true,
      engagements: [{}],
      createdAt: "2023-06-05T16:00:00.000Z",
      updatedAt: "2023-06-08T16:00:00.000Z",
    },
  ];

  const results = memoizedCalendarData(data);

  console.log(results);

  // expect(results).toEqual(memoizeProjectEngagementData);
});

test("memoizeProjectEngagementData() with multiple countries", () => {
  const data = [
    {
      id: "6438f5f51725504e53c94356",
      name: "name of the project",
      registry: {
        id: "6438f5f51725504e53c94356",
        name: "Verra",
      },
      registryProjectId: "1851",
      types: [
        {
          id: "6438f6b71725504e53c94357",
          name: "Renewables",
        },
      ],
      countries: [
        {
          id: "IN",
          name: "India",
          iso2Name: "IN",
          iso3Name: "IND",
        },
        {
          id: "MY",
          name: "Malaysia",
          iso2Name: "MY",
          iso3Name: "MYS",
        },
      ],
      isActive: true,
      engagements: [{}],
      createdAt: "2023-06-05T16:00:00.000Z",
      updatedAt: "2023-06-08T16:00:00.000Z",
    },
  ];

  const results = memoizedCalendarData(data);

  console.log(results);

  // expect(results).toEqual(memoizeProjectEngagementData);
});
