name: s3 static hosting

on:
  push:
    branches:
    - web-new

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy static site to S3 bucket
      run: npm run build-storybook
